### ISSUE TITLE
alternative to using token fragment in route?

### ISSUE THREAD

**Issue by soumyaray** [ISS-Analytics/canvas-lms-visualizations#11]
It might be disconcerting to many to see part of their token as part of their routes.  Any suggestions on alternatives?  For example, using a shortened hash of their token as the id?  I think collisions would be unlikely even with millions of users.

**Comment by stonegold546** [comment]
Nice alternative though I think we needn't use it as the id, but as an extra identifier. The shady way I implemented it, a clash wouldn't matter if it were an extra identifier.
