### ISSUE TITLE
Getting internal server error with new token

### ISSUE THREAD

**Issue by soumyaray** [ISS-Analytics/canvas-lms-visualizations#7]
Entered my token and for the canvas URL I used (https://canvas.instructure.com).  Got internal server error when trying to access link.

**Comment by stonegold546** [comment]
I think I know why. The canvas url needs a backslash, my fault. Will sort this out with a new commit later in the day.

**Comment by soumyaray** [comment]
let me know when you push to heroku -- i'll try it again.

**Comment by soumyaray** [comment]
i had entered a token previously in the db (and put a trailing forward slash '/' in the url), and now it won't even let me see the front page -- internal server error.

**Comment by stonegold546** [comment]
Should work now, restarted the site. I also cleared the database.

**Comment by soumyaray** [comment]
it seems to be working so i'm gonna close this for now
